---
steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    dir: functions/update_hints
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - update_hints
      - --project=${PROJECT_ID}
      - --region=us-central1
      - --runtime=python312
      - --service-account=bee-hints@lukwam-bee.iam.gserviceaccount.com
      - --timeout=30
      - --trigger-http
      - -q
